
name: React app setup

on:
    push:
        branches:
            - main

jobs:

    build-setup:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - run: ls
            - uses: actions/setup-node@v4
              with:
                node-version: '20'
            - run: npm i
            - run: npm run build
            - run: pm2 delete reactappvite || true  # stop old process if running
            - run: pm2 start serve --name "reactappvite" -- -s dist -l 3000
            - run: pm2 save
            - name: Health check
              run: |
                sleep 5  # give it a moment to start up
                curl --fail http://localhost:3000 || (echo "Health check failed!" && exit 1)



