
name: React app setup

on:
    push:
        branches:
            - main

jobs:

    build-setup:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - run: ls
            - uses: actions/setup-node@v4
              with:
                node-version: '20'
            - run: npm i
            - run: npm run build
            - run: npm install -g serve
            - run: serve -s dist -l 3000



